In [3]:
from sklearn.linear_model import LinearRegression

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
x,y = np.arange(10).reshape((5,2)), range(5)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
list(y)

[0, 1, 2, 3, 4]

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
x_train

array([[4, 5],
       [8, 9],
       [0, 1]])

In [9]:
y_train

[2, 4, 0]

In [10]:
x_test

array([[2, 3],
       [6, 7]])

In [11]:
y_test

[1, 3]