In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr3 = np.arange(0,11,2)
arr3

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0,5,20) #linspace using one dimensional array

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [84]:
np.eye(3) # This is for identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(4)

array([0.14152889, 0.09455491, 0.40209785, 0.97237877])

In [20]:
np.random.rand(5,5)

array([[0.39520542, 0.18026943, 0.43202031, 0.60346794, 0.55341887],
       [0.06734679, 0.37422662, 0.00732877, 0.39797917, 0.79774023],
       [0.02009873, 0.49604763, 0.42340337, 0.74399247, 0.30896998],
       [0.57302136, 0.7692553 , 0.12372611, 0.8377752 , 0.03294354],
       [0.26618741, 0.48920833, 0.45000491, 0.18063699, 0.63220049]])

In [21]:
np.random.randint(1,100)

34

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([41, 41, 43, 45, 26, 13, 36, 33, 19,  8])

In [27]:
arr.reshape(5,5) #It should be valid, as we can
#see that above arr is having 25 so the to make
#it 2 dimensional we have to pass valid 
# parameters only i.e 5rows*5columns = 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

45

In [29]:
ranarr.min()

8

In [30]:
ranarr

array([41, 41, 43, 45, 26, 13, 36, 33, 19,  8])

In [32]:
ranarr.argmax() # It gives the index location
# of max value 

3

In [33]:
ranarr.argmin() #It gives you the index value 
# of min value 

9

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

In [40]:
from numpy.random import randint

In [41]:
randint(2,10)

6

In [43]:
np.random.randint(0,100,10)

array([86, 84,  6, 20, 70,  0, 84, 44, 16, 94])

# NumPy Indexing and Selection

In [44]:
import numpy as np

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr = arr.reshape(25)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
slice_of_arr = arr[0:6]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr_copy = arr.copy()

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr_copy[:] = 100

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#Thus we see that untill and unless we create
copy of arr by using arr.copy() the changes what we make to slice_of_arr or any other array it will affect to main array i.e "arr" directly

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0][0]

5

In [63]:
arr_2d[1][1] #OR we can write it as arr_2d[1,1]

25

In [64]:
arr_2d[1,2]

30

In [65]:
bool_arr = arr>10

In [66]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [67]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

# NumPy Operations
    
    #Array with Array
    #Array with Scalars
    #Universal Array Functions

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
arr/arr

<ipython-input-73-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [75]:
arr*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [76]:
1/arr

<ipython-input-76-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [77]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#Universal array functions

In [78]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [80]:
np.max(arr)

10

In [81]:
arr.max()

10

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [83]:
np.log(arr)

<ipython-input-83-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#Refer the documentation of the Universal functions and do the further operations on numpy